// <auto-generated />
namespace FacebookClone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class latest4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(latest4));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131734466_latest4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
